[tool.poetry]
name = "Velexi Research Project Cookiecutter"
version = "0.3.0"
description = "Template for research projects that utilize Jupyter notebooks for exploration, experimentation, analysis, and reporting"
authors = ["Kevin Chu <kevin@velexi.com>"]
license = "Apache"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
cookiecutter = "^1.7.3"
flake8 = "^4.0.1"
pylint = "^2.13.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
