[tool.poetry]
name = "Velexi Research Project Cookiecutter"
version = "0.4.1"
description = "Template for research projects that utilize Jupyter notebooks for exploration, experimentation, analysis, and reporting"
authors = ["Kevin Chu <kevin@velexi.com>"]
license = "Apache License"

[tool.poetry.dependencies]
python = "^3.9"
cookiecutter = "^1.7.3"
coverage = "^6.3.2"
flake8 = "^4.0.1"
pylint = "^2.13.7"
pytest = "^7.1.1"
pytest-cov = "^3.0.0"
pytest-xdist = "^2.5.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
